spring:
  application:
    name:                                               leader-app

  cloud:
    kubernetes:
      leader:
        config-map-name:                              leader

management:
  health:
    livenessState.enabled:                              true
    readinessState.enabled:                             true
