apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-role
  labels:
    app: leader-app
    group: io.mseemann
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["create", "update", "get", "list", "watch"]
