apiVersion: v1
kind: Service
metadata:
  name: leader-app-service
  namespace: poc
spec:
  selector:
    app: leader-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
